apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vici-cdr-scrubber
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 8
      timeoutSeconds: 3600
      containers:
        - image: gcr.io/YOUR_PROJECT_ID/vici-cdr-scrubber
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_PATH
              value: "/root/config.yaml"
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 30
  traffic:
    - latestRevision: true
      percent: 100
